/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
window.IFrameElement=window.IFrameElement||{EmptyRelatedListDoc:"emptyHtmlDoc.html"};function isWindowAccessible(a){var b=null;try{b=a.location.href}catch(c){}return"string"===typeof b}function getAccessibleParentWindow(a){return a==window.top?null:!isWindowAccessible(a.parent)?null:a.location.pathname==="/"+IFrameElement.EmptyRelatedListDoc?a.getAccessibleParentWindow(a.parent):a.parent}window.parentWindow=getAccessibleParentWindow(self);
window.Sfdc=window.Sfdc||{};
Sfdc.servicedeskLinksMonitor=function(){function b(a){if(a)return"string"===typeof a.href?decodeURI(a.href).match(Sfdc.servicedeskLinksMonitor.SRCUP_URL_REGEXP)?a:void 0:b(a.parentElement)}var c=function(a){a=a||window.event;var c=b(a.target||a.srcElement);if(void 0!==c&&(a.ctrlKey||a.metaKey))a.preventDefault?a.preventDefault():a.returnValue=!1,srcUp(Sfdc.servicedeskLinksMonitor.extractSrcUpUrl(c.href),!1,!0)};return{init:function(){document.attachEvent?document.attachEvent("onclick",c):document.addEventListener("click",
c,!1)}}}();Sfdc.servicedeskLinksMonitor.SRCUP_URL_REGEXP=/javascript\:srcUp\('(.*)'\);/;Sfdc.servicedeskLinksMonitor.extractSrcUpUrl=function(b){b=decodeURI(b);var c=b.match(Sfdc.servicedeskLinksMonitor.SRCUP_URL_REGEXP);c&&(b=decodeURIComponent(c[1]));return b};Sfdc.servicedeskLinksMonitor.init();
window.Sfdc=window.Sfdc||{};Sfdc.xdomain=Sfdc.xdomain||{};
Sfdc.xdomain.Listener=Sfdc.xdomain.Listener||function(){function a(b,a){var c={};c.pathToTargetProxy=b.pathToOriginProxy;c.name=b.args.event?b.name:b.name+"_"+b.txnId;"undefined"!==typeof a&&(c.targetParentFrame=a);c.calleeName=b.originFrame;c.txn_id=b.txnId;return function(a){Sfdc.xdomain.Util.usePostMessage(b)?(c.args=Sfdc.xdomain.Parser.stringify(a),Sfdc.xdomain.PostMessage.doPostMessage(b,c)):(c.args=a,Sfdc.xdomain.Caller.call(c))}}return{accept:function(b){var e;e="sfdc-console"===b.targetFrame?
Sfdc.crossdomain.CrossDomainApiRegistry.getFunction(b.name):Sfdc.xdomain.CrossDomainApiRegistry.getFunction(b.name);var c={},f;"undefined"!==typeof Sfdc.xdomain.EmbeddedVFPages&&"undefined"!==typeof Sfdc.xdomain.EmbeddedVFPages[b.originFrame]?(c.frameId=Sfdc.xdomain.EmbeddedVFPages[b.originFrame],f=c.frameId):c.frameId=b.originFrame;c.pathToOriginProxy=b.pathToOriginProxy;"undefined"!==typeof e&&e.func.call(e.scope,b.args,c,a(b,f))}}}();
Sfdc.xdomain.Caller=Sfdc.xdomain.Caller||function(){function a(a){window.addEventListener?this.removeEventListener("load",arguments.callee,!1):window.attachEvent&&this.detachEvent("onload",arguments.callee);var e=a.srcElement?a.srcElement:a.target;setTimeout(function(){e.parentNode.removeChild(e)},10)}return{call:function(b){var e=b.calleeName+"_proxyFrame_"+b.txn_id,c={};"undefined"!==typeof b.name&&(c.xdomain_name=b.name);"undefined"!==typeof b.calleeName&&(c.xdomain_targetFrame=b.calleeName);"undefined"!==
typeof b.txn_id&&(c.xdomain_txnId=b.txn_id);"undefined"!==typeof b.pathToOriginProxy&&(c.xdomain_pathToOriginProxy=b.pathToOriginProxy);"undefined"!==typeof b.targetParentFrame&&(c.xdomain_targetParentFrame=b.targetParentFrame);c.xdomain_originFrame=window.name;c=Sfdc.xdomain.Parser.stringify(c);"undefined"!==typeof b.args&&(c+="\x26"+Sfdc.xdomain.Parser.stringify(b.args));b=b.pathToTargetProxy;if("undefined"!==typeof b){var f=document.createElement("iframe");f.id=e;f.name=e;f.src=b+"#"+c;f.width=
10;f.height=10;f.frameborder=0;f.style.position="absolute";f.style.left="-150px";f.style.top="0px";window.addEventListener?f.addEventListener("load",a,!1):window.attachEvent&&f.attachEvent("onload",a);document.body.appendChild(f)}}}}();Sfdc.xdomain.CrossDomainApiRegistry=Sfdc.xdomain.CrossDomainApiRegistry||function(){var a={};return{registerFunction:function(b,e,c){a[b]={func:e,scope:c}},getFunction:function(b){return a[b]},removeFunction:function(b){delete a[b]}}}();
Sfdc.xdomain.Parser=Sfdc.xdomain.Parser||function(){return{parse:function(a){var b={};a=a.split("\x26");for(var e=0;e<a.length;e++){var c=a[e].split("\x3d"),f=c[1].split(":"),k;if("a"===f[0]){var m=f[1].split(";");k=[];for(var g=0;g<m.length;g++)k[g]=decodeURIComponent(m[g])}else k=decodeURIComponent(f[1]);"b"===f[0]&&(k="true"===k);b[decodeURIComponent(c[0])]=k}return b},stringify:function(a){var b="",e="",c;for(c in a)if(a.hasOwnProperty(c)){var f;if("[object Array]"===Object.prototype.toString.apply(a[c])){b=
b+encodeURIComponent(c)+"\x3da:";f=a[c];for(var k="",m="",g=0;g<f.length;g++)m+=k+encodeURIComponent(f[g]),k=";";e+=b+m}else f="boolean"===typeof a[c]?"b":"s",e+=b+encodeURIComponent(c)+"\x3d"+f+":"+encodeURIComponent(a[c]);b="\x26"}return e}}}();
Sfdc.xdomain.Query=Sfdc.xdomain.Query||function(a){a=Sfdc.xdomain.Parser.parse(a);"undefined"!==typeof a.xdomain_targetFrame&&(this.targetFrame=a.xdomain_targetFrame,delete a.xdomain_targetFrame);"undefined"!==typeof a.xdomain_originFrame&&(this.originFrame=a.xdomain_originFrame,delete a.xdomain_originFrame);"undefined"!==typeof a.xdomain_name&&(this.name=a.xdomain_name,delete a.xdomain_name);"undefined"!==typeof a.xdomain_txnId&&(this.txnId=a.xdomain_txnId,delete a.xdomain_txnId);"undefined"!==typeof a.xdomain_pathToOriginProxy&&
(this.pathToOriginProxy=a.xdomain_pathToOriginProxy,delete a.xdomain_pathToOriginProxy);"undefined"!==typeof a.xdomain_targetParentFrame&&(this.targetParentFrame=a.xdomain_targetParentFrame,delete a.xdomain_targetParentFrame);this.args=a};
Sfdc.xdomain.Util=Sfdc.xdomain.Util||function(){return{isInServiceDesk:function(){return Sfdc&&Sfdc.support&&Sfdc.support.servicedesk},isPostMessage:function(){return!!window.postMessage},usePostMessage:function(a){return!Sfdc.userAgent.isIE8&&Sfdc.xdomain.Util.isInServiceDesk()&&Sfdc.xdomain.Util.isPostMessage()&&("private_api"===a.args.version||25<parseInt(a.args.version,10))&&!!a.args.nonce&&!!a.xdomainOrigin}}}();
Sfdc.xdomain.PostMessage=Sfdc.xdomain.PostMessage||function(){function a(a){if(Sfdc.xdomain.Util.isInServiceDesk()&&Sfdc.support.servicedesk.checkWhiteList(a.origin)&&!(a.data&&0!==a.data.indexOf(b))){var c=a.data.replace(b,""),c=new Sfdc.xdomain.Query(c);c.xdomainOrigin=a.source;c.args.nonce&&c.args.nonce===Sfdc.support.servicedesk.API_NONCE&&Sfdc.xdomain.Listener.accept(c)}}var b="integrationApi/";Sfdc.xdomain.Util.isInServiceDesk()&&Sfdc.xdomain.Util.isPostMessage()&&(window.attachEvent?window.attachEvent("onmessage",
a):window.addEventListener("message",a,!1));return{doPostMessage:function(a,c){a.xdomainOrigin.postMessage(b+Sfdc.xdomain.Parser.stringify(c),c.pathToTargetProxy)}}}();window.privateapi=window.privateapi||{};
privateapi.console=function(){function a(l,a,b){if(b.event){var d;if(l===c)return d={},d[b.eventType]=[a],function(){return{add:function(l,a){var b=!0;d[a.eventType]||(b=!1,d[a.eventType]=[]);d[a.eventType].push(l);return b},del:function(l,a){var b=d[a.eventType],q={unregisterFrameForEvent:!1,unregisterFrameForEveryEvent:!1};if(!b)return q;for(var n=0;n<b.length;n++)if(b[n]===l){b.splice(n,1);break}0===b.length&&(q.unregisterFrameForEvent=!0);for(var e in d)if(d.hasOwnProperty(e)&&0<d[e].length)return q;
q.unregisterFrameForEveryEvent=!0;p.removeFunction(c);return q},call:function(l,a,b,q){var c=d[a.eventType]?d[a.eventType]:[];delete a.eventType;for(var n=0;n<c.length;n++)c[n].call(l,a,b,q)}}}()}else return function(b){p.removeFunction(l);a.call(this,b)}}function b(l,b,c){b.version=f;if("undefined"!==typeof c){var d=b.event?l:l+"_"+m;if(b.event&&p.getFunction(d)){if(p.getFunction(d).func.add(c,b))return}else p.registerFunction(d,a(d,c,b),this)}c={};c.pathToTargetProxy=g?Sfdc.xdomain.sfdcXDomainProxy:
"";c.name=l;c.args=b;c.calleeName=k;c.txn_id=m;d=window.location.toString();l=["/","?","#"];b="";if(-1!==d.indexOf("://")){d=d.split("://");b=d[0]+"://";for(var d=d[1],e=0;e<l.length;e++){var r=d.indexOf(l[e]);if(-1!==r){d=d.substring(0,r);break}}}c.pathToOriginProxy=b+d+(g?"/crossDomainProxy.html":"");m++;h.usePostMessage()?h.doPostMessage(c):g.call(c)}function e(a,b,c){a.href&&(a=a.href);if(-1<a.indexOf("script:"))window.location=a;else{var d=QueryString.createQueryString(a,!0);d.get(Desktop.IS_DESKTOP)||
(d.add(Desktop.IS_DESKTOP,"vw"),a=QueryString.getURI(a)+d.toString());if(d="DETAIL"===b){a:switch(c){case "clone":case "share":case "adv":case "newTask":case "newEvent":c=!0;break a;default:c=!1}d=!c}d||"DASHBOARD"===b||"CONTENT"===b||"REPORT"===b||"CAMPAIGN"===b||"CHATTER"===b||"SHARE"===b||"ACCOUNT_SALES_TEAM"===b||"OPP_SALES_TEAM"===b?(a=h.addQueryString(a),this.srcSelf(a)):this.srcUp(a)}}var c="addEventListener",f="private_api",k="sfdc-console",m=0,g,p,h={nonce:null,sfdcOrigin:null,INTEGRATION_API:"integrationApi/",
usePostMessage:function(){var a=this.parseUrlQueryString(location.search);this.sfdcOrigin=a.sfdcIFrameOrigin;this.nonce=a.nonce;return!Sfdc.userAgent.isIE8&&!!window.postMessage&&a.sfdcIFrameOrigin&&a.nonce},initialize:function(){window.attachEvent?window.attachEvent("onmessage",this.processPostMessage):window.addEventListener("message",this.processPostMessage,!1)},registry:function(){var a={};return{registerFunction:function(b,c,d){a[b]={func:c,scope:d}},getFunction:function(b){return a[b]},removeFunction:function(b){delete a[b]}}}(),
doPostMessage:function(a){var b={};"undefined"!==typeof a.name&&(b.xdomain_name=a.name);"undefined"!==typeof a.calleeName&&(b.xdomain_targetFrame=a.calleeName);"undefined"!==typeof a.txn_id&&(b.xdomain_txnId=a.txn_id);"undefined"!==typeof a.pathToOriginProxy&&(b.xdomain_pathToOriginProxy=a.pathToOriginProxy);"undefined"!==typeof a.targetParentFrame&&(b.xdomain_targetParentFrame=a.targetParentFrame);b.xdomain_originFrame=window.name;b.nonce=this.nonce;b=Sfdc.xdomain.Parser.stringify(b);"undefined"!==
typeof a.args&&(b+="\x26"+Sfdc.xdomain.Parser.stringify(a.args));top.postMessage(this.INTEGRATION_API+b,this.sfdcOrigin)},processPostMessage:function(a){var b={},c;a.origin===h.sfdcOrigin&&!(a.data&&0!==a.data.indexOf(h.INTEGRATION_API))&&(a=a.data.replace(h.INTEGRATION_API,""),c=Sfdc.xdomain.Parser.parse(a),c.args=Sfdc.xdomain.Parser.parse(c.args),a=p.getFunction(c.name),b.frameId=c.originFrame,"undefined"!==typeof a&&a.func.call(a.scope,c.args,b))},parseUrlQueryString:function(a){var b={};if("string"!==
typeof a)return b;"?"===a.charAt(0)&&(a=a.slice(1));if(0===a.length)return b;a=a.split("\x26");for(var c=0;c<a.length;c++){var d=a[c].split("\x3d");b[d[0]]=d[1]?decodeURIComponent(d[1]):null}return b},addQueryString:function(a){a=a.split("#");var b=a.splice(0,1)[0],c=Sfdc.Url.getUrlParameters(b,{allowMultipleOfParam:!0}),d=Sfdc.Url.getUrlParameters(window.location.href);c[Desktop.NONCE]=d[Desktop.NONCE];c[Desktop.SFDCIFRAMEORIGIN]=d[Desktop.SFDCIFRAMEORIGIN];b=Sfdc.Url.generateQueryString(QueryString.getURI(b),
c,{fullUrl:!0,allowMultipleOfParam:!0});0<a.length&&(b+="#"+a.join("#"));return b}};h.usePostMessage()?(p=h.registry,h.initialize(),window.navigateToUrl=e):window.Sfdc&&Sfdc.xdomain?(g=Sfdc.xdomain.Caller,p=Sfdc.xdomain.CrossDomainApiRegistry,window.navigateToUrl=e):window.console&&console.log&&console.log("Service Cloud Toolkit API cannot be used with your browser.");return{openPrimaryTab:function(a,c,e,d,f,k){var g={};a&&(g.id=a);"undefined"!==typeof c&&(g.url=c);"undefined"!==typeof e&&(g.activate=
!!e);"undefined"!==typeof d&&(g.label=d);"undefined"!==typeof k&&(g.name=k);b("openPrimaryTab",g,f)},openSubtab:function(a,c,e,d,f,g,k,m){var h={};a&&(h.workspaceId=a);"undefined"!==typeof c&&(h.url=c);"undefined"!==typeof e&&(h.activate=!!e);"undefined"!==typeof d&&(h.label=d);f&&(h.id=f);k&&(h.name=k);m&&(h.openInBackground=m);b("openSubTab",h,g)},hasEnclosingSubtabFocus:function(a){b("hasEnclosingSubtabFocus",{"":""},a)},getFocusedPrimaryTabId:function(a){b("getFocusedPrimaryTabId",{"":""},a)},
relayKeyEvent:function(a){var c={};c.keyCode=a.keyCode;c.ctrlKey=!!a.ctrlKey;c.altKey=!!a.altKey;c.shiftKey=!!a.shiftKey;b("relayKeyEvent",c)},refreshActiveTab:function(a){var c={};c.forceFullRefresh=a;b("refreshActiveTab",c)},addEventListener:function(a,e){if(a&&"string"===typeof a&&e&&"function"===typeof e){var f={event:!0};f.eventType=a;b(c,f,e)}},fireEvent:function(a,c,e){if(a&&"string"===typeof a){var d={};d.eventType=a;d.message=c;b("fireEvent",d,e)}},cti:{isClickToDialEnabled:function(a){b("isClickToDialEnabled",
{},a)},sendCTIMessage:function(a){b("sendCTIMessage",{msg:a})}}}}();function getSdParentCmp(a){return a==window.top?null:!isWindowAccessible(a.parent)?null:a.parent.sdParentCmp?a.parent.sdParentCmp:getSdParentCmp(a.parent)}function attachObservers(){if(window.SfdcCmp)for(var a=window.SfdcCmp.getTypeInstances("SfdcCmp.Data.ListServletProvider"),b=0,e=a.length;b<e;b++)a[b].attach("onsend",window.handleListProviderSend)}
function handleListProviderSend(a,b){DesktopContext.preserveDesktopPageParam(window.location.href,b.params)}function isInNavTab(){return"nv"===Sfdc.Url.getUrlParameters(window.location.href)[Desktop.IS_DESKTOP]}function srcSelf(a){window.location.href=a}
function srcUp(a,b,e){if(window.sdParentCmp)window.top.Perf.autoMark(),window.sdParentCmp.fireNavigatePage(a,void 0,void 0,e);else{var c=getSdParentCmp(window);navigator.userAgent.toLowerCase();if(c)c.fireNavigatePage(a,void 0,void 0,e);else try{Sfdc.xdomain.Caller&&window.self!==window.top?window.isInNavTab()||b?window.privateapi.console.openPrimaryTab(null,a,!0,!1):window.privateapi.console.getFocusedPrimaryTabId(function(b){b.success&&b.id?window.privateapi.console.openSubtab(b.id,a,!0,!1,null,
void 0,void 0,e):srcSelf(a)}):srcSelf(a)}catch(f){srcSelf(a)}}}if(Sfdc.onload)Sfdc.onload(function(){Sfdc.resolve("Sfdc.canvas.parent.subscribe")&&privateapi.console.addEventListener("PublisherEvent_"+window.name,function(a){window.postMessage(a.message,"*")})});
window.Sfdc=window.Sfdc||{};
Sfdc.servicedeskview=function(){var k=/javascript\:srcUp\('(.*)'\);/,d,c,e=function(a){this.element=a};e.prototype.focus=function(){Ext.fly(this.element).addClass("highlight")};e.prototype.unfocus=function(){Ext.fly(this.element).removeClass("highlight")};e.prototype.openLink=function(){var a=decodeURIComponent(Ext.fly(this.element).first(".dataCell").first("a").getAttribute("href"));DesktopContext.isUrlNavigatorEnable()?srcUp(Sfdc.servicedeskUrlNavigator.preservePageType(a)):(a=a.match(k))&&a[1]&&
srcUp(a[1])};var f=function(a){this.currentPosition=-1;this.size=a.length;this.rows=[];for(var b=0;b<a.length;b++)this.rows.push(new e(a[b]))};f.prototype.selectNext=function(){0!==this.size&&(this.rows[this.currentPosition]&&this.rows[this.currentPosition].unfocus(),this.currentPosition=++this.currentPosition%this.size,this.rows[this.currentPosition].focus())};f.prototype.selectPrevious=function(){0!==this.size&&(this.rows[this.currentPosition]&&this.rows[this.currentPosition].unfocus(),this.currentPosition=
-1===this.currentPosition?this.currentPosition+this.size:(--this.currentPosition+this.size)%this.size,this.rows[this.currentPosition].focus())};f.prototype.openFocusedRowLink=function(){this.rows[this.currentPosition]&&this.rows[this.currentPosition].openLink()};var l={27:!0,"ctrl+83":!0},g=function(a){var b=null;try{b=a.location.href}catch(c){}return"string"!==typeof b},m=function(a){var b=document.activeElement.tagName.toUpperCase();if(!(b=!("INPUT"===b||"TEXTAREA"===b||"SELECT"===b)))b=[],a.ctrlKey&&
b.push("ctrl"),a.altKey&&b.push("alt"),a.shiftKey&&b.push("shift"),a.keyCode&&b.push(a.keyCode),b=!!l[b.join("+")];b&&(d=document.activeElement,g(top)?privateapi.console.relayKeyEvent(a):top.Sfdc&&(top.Sfdc.support&&top.Sfdc.support.servicedesk&&top.Sfdc.support.servicedesk.HotkeyEngine)&&top.Sfdc.support.servicedesk.HotkeyEngine.executeCommand(a))},h=function(){return window.SearchPage&&window.sfdcPage instanceof window.SearchPage||window.UnifiedSearchPage&&window.sfdcPage instanceof window.UnifiedSearchPage};
return{navigateToEditPage:function(){if(window.Sfdc){var a=Sfdc.get('.btn[name\x3d"edit"]');if(a&&a.onclick)a.onclick()}},savePage:function(){if(window.Sfdc){var a=Sfdc.get('.btn[name\x3d"save"]');a||(a=Sfdc.get('.btn[name\x3d"inlineEditSave"]'));a&&a.click&&a.click()}},focusDetailView:function(){window.focus();d&&d.focus&&d.focus()},selectNextSearchResultRow:function(){c&&c.selectNext()},selectPreviousSearchResultRow:function(){c&&c.selectPrevious()},openFocusedSearchResultRowLink:function(){c&&
c.openFocusedRowLink()},isUnifiedSearchPage:function(){return h()},isKeyEventMappedToAHotkeyCommand:function(a){return g(top)?!1:top.Sfdc&&top.Sfdc.resolve("Sfdc.support.servicedesk.HotkeyEngine")&&top.Sfdc.support.servicedesk.HotkeyEngine.isKeyEventMappedToAHotkeyCommand(a)?!0:!1},initHotkey:function(){if(window.Sfdc&&Sfdc.onload)Sfdc.onload(function(){Sfdc.on(document,"keydown",m);h()&&(c=new f(Ext.query("#searchResultsHolderDiv .dataRow")));g(top)&&privateapi.console.addEventListener("HotkeyEvent_"+
window.name,function(a){a=a.message;"EDIT"===a?Sfdc.servicedeskview.navigateToEditPage():"SAVE"===a?Sfdc.servicedeskview.savePage():"FOCUS_DETAIL_VIEW"===a&&Sfdc.servicedeskview.focusDetailView()})})}}}();Sfdc.servicedeskview.initHotkey();

//# sourceMappingURL=/javascript/1426154839000/sfdc/source/ServiceDeskView.js.map
