/*------------------------------------------------------------
Author:        Vishnu Belkone
Company:       Arxxus.com
Description:   Test Class for Action Plan sharing rules.


History
08/05/2015     Vishnu Belkone       Created
------------------------------------------------------------*/
@isTest
public class ActionPlanPDFGenerator_Test {
    static testMethod void generateActionPlanPDF() {
        
    }
}