/**
 * @Author: Sauce Consulting
 * @Description: The Service Locator class is used to provide the endpoints required by the service
 * TestClass :      
 * History
 * Date            Author                      Comments
   --------------------------------------------------------------------------------------
   6-11-2019       Sauce Consulting            Initial Release
 */
public interface NSWPointServiceLocator{

    /**
     * provide the endpoint for the service
     */
    String endpoint();    
}