/**
 * @Author: Sauce Consulting
 * @Description: NSW point service request builder interface
 * TestClass :      
 * History
 * Date            Author                      Comments
   ------------------------------------------------------------
   6-11-2019       Sauce Consulting            Initial Release
 */
public interface NSWPointServiceRequestBuilder {
    NSWPointServiceRequest buildRequest(Object reqParams);
}