/**
 * @Author: Sauce Consulting
 * @Description: NSW point service response parser interface
 * TestClass :      
 * History
 * Date            Author                      Comments
   --------------------------------------------------------------------------------------
   6-11-2019       Sauce Consulting            Initial Release
 */
public interface NSWPointServiceResponseParser {
   
    void parse(NSWPointServiceResponse response);    
}