/*------------------------------------------------------------
    Author:         Ian Huang
    Company:        Salesforce.com
    Description:    Provides an enhanced UI for managing Case printing item Requires Printing flag and Sequence  
    Inputs:         
    Returns:        
    History:
    ------------------------------------------------------------*/  
public class PrintingItemController {

    public PrintingItemController() {
        //
    } 
 
}